language: java
sudo: false
install:
  - true
  - chmod +x gradlew
addons:
  sonarcloud:
    organization: "gopinath-langote"
    token:
      secure: "15d9f8fc3135b0217d308bcb85e5aa067831d92f"
jdk:
  - oraclejdk8
script:
  - ./gradlew sonarqube
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'