language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "gopinath-langote-github"
    token:
      secure: "32fde44377d6503c7ac6af91e7b6cb230664286e"
jdk:
  - oraclejdk8
script:
  - ./gradlew sonarqube
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'